|#9ÖÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ·
|#9º|#4                           WWIV Chatroom Help                                |#9º
|#9ÓÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ½

|#1                Command|#9                      What it does
|#2                -------                      ------------
|#1                ?                            |#9Displays this menu
|#1                /q or x                      |#9Exits chat
|#1                /c                           |#9Changes chat channels
|#1                /s                           |#9Secures a chat channel
|#1                /u                           |#9Unsecures a chat channel
|#1                /p                           |#9Pages a user
|#1                /w                           |#9Display who's online
|#1                /a                           |#9Toggles action mode 
|#1                list                         |#9Displays a list of actions
|#1                (action name) ?              |#9Displays help on an action
|#1                GA                           |#9Executes a generic action
|#1                >username msg                |#9Direct a message to a user 
|#1                /username msg                |#9Whispers a message to a user or
|#9                                             sends a message to someone
|#9                                             outside of chat.
