    Glad you could drop by!  It's always a pleasure to have a Sysop visit!
Double-check your information in [D]efaults and, if something's not correct,
please correct it.  Remember, WWIV modifications are only accessible after
your registration number is provided.  As a Sysop, I'm sure you know your way
around the BBS, so I won't bore you with overviews or rules!  Help yourself
to whatever's here and enjoy!
