#!/bin/bash
#
# WWIV Build Script.
#
# Required Variables:
#   WORKSPACE - Jenkins workspace
#   BUILD_NUMBER - Jenkins Build number


# Runs a single test collecting the output into
# ${test_name}.xml (i.e. core-test.xml)
#
# Args:
# 1: test dir i.e. ${WORKSPACE}/core_tests
# 2: test name, no suffic (i.e. core-test)
run_test() {
    set +e
    local test_dir=$1
    local test_name=$2
    if [[ -z "${test_dir}" ]]; then
    echo "test_dir must be specified to run_test"
    exit 1;
    fi
    if [[ -z "${test_name}" ]]; then
    echo "test_name must be specified to run_test"
    exit 1;
    fi

    cd "${test_dir}"
    if [[ -r result.xml ]]; then
    rm result.xml
    fi

    ./${test_name} --gtest_output=xml:result-${test_name}.xml
    cd ${WORKSPACE}
    set -e
}

rm ${WORKSPACE}/wwiv-*.tar.gz

set -e

declare -r CMAKE_BINARY_DIR="${WORKSPACE}/_build"
declare -r WWIV_RELEASE_DIR="${WORKSPACE}/release"
delcare -r WWIV_INSTALL_SRC="${WORKSPACE}/install"
declare -r WWIV_RELEASE="5.5"
declare -r WWIV_FULL_RELEASE="5.5.0"
declare -r WWIV_RELEASE_ARCHIVE_FILE=${WORKSPACE}/wwiv-linux-${label}-${WWIV_RELEASE}.${BUILD_NUMBER}.tar.gz
declare -r CTEST_BIN=ctest
echo "WWIV BBS Build"
echo "Workspace:        ${WORKSPACE}"
echo "CMake:            ${CMAKE_BIN}"
echo "CTest:            ${CTEST_BIN}"
echo "CMake Build:      ${CMAKE_BINARY_DIR}"
echo "Release Dir:      ${WWIV_RELEASE_DIR}"
echo "WWI Full Release: ${WWIV_FULL_RELEASE}"
echo "WWIV Release:     ${WWIV_RELEASE}"
echo "Version:          ${BUILD_NUMBER}"
echo "Archive:          ${WWIV_RELEASE_ARCHIVE_FILE}"
echo "Label:            ${label}"
echo "GCC:              $(gcc --version)"

echo "Ensuring CMAKE_BINARY_DIR exists: (${CMAKE_BINARY_DIR})"
if [[ ! -d "${CMAKE_BINARY_DIR}" ]]; then
  mkdir -p "${CMAKE_BINARY_DIR}"
fi
echo "Created release dir: ${WWIV_RELEASE_DIR}"

echo "Cleaning up release dir (${WWIV_RELEASE_DIR})"
if [[ -d "${WWIV_RELEASE_DIR}" ]]; then
  rm -rf "${WWIV_RELEASE_DIR}"
fi
mkdir -p "${WWIV_RELEASE_DIR}"
echo "Created release dir: ${WWIV_RELEASE_DIR}"

echo "Building binaries"
cd ${WORKSPACE}
sed -i -e "s@.development@.${BUILD_NUMBER}@" core/version.cpp

echo "Compiling Everything"
if [[ ! -d "${CMAKE_BINARY_DIR}" ]]; then
    mkdir -p ${CMAKE_BINARY_DIR}
fi

pushd ${CMAKE_BINARY_DIR}
${CMAKE_BIN} -G "Ninja" -DCMAKE_BINARY_DIR_TYPE=Debug ..
${CMAKE_BIN} --build . --config Debug

run_test "${CMAKE_BINARY_DIR}/core_test" core_tests
run_test "${CMAKE_BINARY_DIR}/sdk_test" sdk_tests
run_test "${CMAKE_BINARY_DIR}/binkp_test" binkp_tests
run_test "${CMAKE_BINARY_DIR}/net_core_test" net_core_tests
run_test "${CMAKE_BINARY_DIR}/bbs_test" bbs_tests
run_test "${CMAKE_BINARY_DIR}/wwivd_test" wwivd_tests

cd ${CMAKE_BINARY_DIR}
${CTEST_BIN} --no-compress-output -T Test -V || /bin/true
cd ${WORKSPACE}

echo "Populating built binaries"
cp  ${CMAKE_BINARY_DIR}/bbs/bbs \
    ${CMAKE_BINARY_DIR}/network/network \
    ${CMAKE_BINARY_DIR}/networkb/networkb \
    ${CMAKE_BINARY_DIR}/networkc/networkc \
    ${CMAKE_BINARY_DIR}/networkf/networkf \
    ${CMAKE_BINARY_DIR}/networkt/networkt \
    ${CMAKE_BINARY_DIR}/network1/network1 \
    ${CMAKE_BINARY_DIR}/network2/network2 \
    ${CMAKE_BINARY_DIR}/network3/network3 \
    ${CMAKE_BINARY_DIR}/wwivconfig/wwivconfig \
    ${CMAKE_BINARY_DIR}/wwivd/wwivd \
    ${CMAKE_BINARY_DIR}/wwivutil/wwivutil \
    ${WWIV_RELEASE_DIR}

echo "adding common files"

echo "adding linux-specific files"
cd ${WWIV_INSTALL_SRC}/platform/unix
shopt -s dotglob
cp -a * ${WWIV_RELEASE_DIR}
shopt -u dotglob

echo "Creating release archive: ${WWIV_RELEASE_ARCHIVE_FILE}"
cd ${WWIV_RELEASE_DIR}
shopt -s dotglob
tar zcvf ${WWIV_RELEASE_ARCHIVE_FILE} * 
shopt -u dotglob

echo "Archive file: ${WWIV_RELEASE_ARCHIVE_FILE}"
echo "File Contents:"
tar ztvf ${WWIV_RELEASE_ARCHIVE_FILE}
