#!/bin/bash
#
# WWIV Build Script.
#
# Required Variables:
# WORKSPACE - Jenkins workspace
# BUILD_NUMBER - Jenkins Build number
# WWIV_TEST_TEMPDIR - test tempdir to use.

source ${WORKSPACE}/builds/jenkins/wwiv/build.bash

rm ${WORKSPACE}/wwiv-build-linux-*.tar.gz

set -e

declare -r CMAKE_BUILD="${WORKSPACE}/_build"
echo "WWIV BBS Tests"
echo "Workspace:         ${WORKSPACE}"
echo "Version:           ${BUILD_NUMBER}"
echo "Archive:           ${RELEASE_TGZ}"
echo "WWIV_TEST_TEMPDIR: ${WWIV_TEST_TEMPDIR}"

if [[ -z "${WWIV_TEST_TEMPDIR}" ]]; then
    echo "WWIV_TEST_TEMPDIR must be set."
    exit 1
fi

if [[ ! -d "${WWIV_TEST_TEMPDIR}" ]]; then
    mkdir ${WWIV_TEST_TEMPDIR}
    echo "Created directory: ${WWIV_TEST_TEMPDIR}"
fi

build_binaries -j8

run_test "${CMAKE_BUILD}/core_test" core_tests
run_test "${CMAKE_BUILD}/sdk_test" sdk_tests
run_test "${CMAKE_BUILD}/networkb_test" networkb_tests
run_test "${CMAKE_BUILD}/bbs_test" bbs_tests
    
