|#2                              WWIV Editor Commands
|#7~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    |#1/?            |#9 Display WWIV Editor help (this screen)
    |#1/S            |#9 Save Message
    |#1/Q            |#9 Quote text from original message.
    |#1/ESY          |#9 Save Message Anonymously
    |#1/ESN          |#9 Save Message NOT Anonymously
    |#1/ABT          |#9 Abort Entire Message (Quit)
    |#1/CLR          |#9 Clear Message and Start Over
    |#1/RL           |#9 Replace Last Line
    |#1/TI           |#9 Edit Message Title
    |#1/LI           |#9 List Message So Far
    |#1/C:           |#9 Center Text After "/C:"

    |#1/SU/Old/New   |#9 Replace Old Text with New
    |#1CTRL-P+ 0 - Z |#9 Change Color to Digit
|#7~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

