|#5Arrow Keys:
|#9(|#2Up|#9)     |#9Scroll Up                  |#9(|#2Down|#9)     |#9Scroll Down
|#9(|#2Left|#9)   |#9Previous Message           |#9(|#2Right|#9)    |#9Next Message
|#9(|#2ENTER|#9)  |#9Read Next Message

|#5Commands:
|#9(|#2A|#9) E-Mail Author of Last Message        
|#9(|#2P|#9) Post a Public Message in Current Sub   
|#9(|#2Q|#9) Quit to Main Menu                      
|#9(|#2W|#9) Reply with "Regards" to Last Message 

