WWIV v5.00 uses a new menu system that allows you to select from a variety
of menu types, providing you with a new level of individual configuration.
Each menu set provides an option for both standard and pulldown styles, as
well as a "hot-key" support toggle.

After selecting your default menu set, you can change them by typing //CM
('Change Menus') from the main menu. Remember, if hotkey support is turned
off, you do not need the '//' before multi-letter commands.

Please select a menu set from the menus listed below:
