|#5€ﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂ|#4 CO-SYSOP COMMANDS |#5ﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂ€
|#5›                                  ﬁ› |#2//|#1STATUS    |#3=|#5 Current System Status ﬁ
|#5›  |#1,       |#3=|#5 Verbose Net Logs      ﬁ› |#2//|#1PENDING   |#3=|#5 Network Mail Pending  ﬁ
|#5› |#2//|#1LOG    |#3=|#5 Today's Sysop Log     ﬁ› |#2/|#1V          |#3=|#5 Validate Msgs.        ﬁ
|#5› |#2//|#1NLOG   |#3=|#5 Network Connection Logﬁ› |#2//|#1!         |#3=|#5 Validate a User       ﬁ
|#5› |#2//|#1YLOG   |#3=|#5 Yesterday's Sysop Log ﬁ› |#2//|#1IVOTES    |#3=|#5 Initialize Voting Dat ﬁ
|#5› |#2//|#1ZLOG   |#3=|#5 System Activity Log   ﬁ› |#2//|#1VOTEPRINT |#3=|#5 Voting Data to File   ﬁ
|#5›                                  ﬁ›                                     ﬁ
|#5€€€€€€€€€€€€€€€€€€€€€€€€€€€€|#4 SYSOP COMMANDS |#5€€€€€€€€€€€€€€€€€€€€€€€€€€€€€€€
|#5€                                  ﬁ›                                     €
|#5› |#2//|#1AE    |#3=|#5 Allowed Files Editor   ﬁ› |#2//|#1CHAT       |#3=|#5 Toggle Chat Avail.   ﬁ
|#5› |#2//|#1BE    |#3=|#5 Message Board Editor   ﬁ› |#2//|#1DOS        |#3=|#5 Shell to DOS         ﬁ
|#5› |#2//|#1CE    |#3=|#5 Chain (Door) Editor    ﬁ› |#2//|#1EDIT       |#3=|#5 Edit Any Text File   ﬁ
|#5› |#2//|#1DE    |#3=|#5 Directory Editor       ﬁ› |#2//|#1LOAD       |#3=|#5 Load File in Editor  ﬁ
|#5› |#2//|#1EE    |#3=|#5 Event Editor           ﬁ› |#2//|#1MAILR      |#3=|#5 Read All Mail Sent   ﬁ
|#5› |#2//|#1EM    |#3=|#5 Menu Editor            ﬁ› |#2//|#1PACK       |#3=|#5 Pack Msg Base        ﬁ
|#5› |#2//|#1GE    |#3=|#5 G-File Editor          ﬁ› |#2//|#1REBOOT     |#3=|#5 Reboot WWIV Computer ﬁ
|#5› |#2//|#1IE    |#3=|#5 Instance Editor        ﬁ› |#2//|#1RELOAD     |#3=|#5 Reload All Menu File ﬁ
|#5› |#2//|#1JE    |#3=|#5 Conference Editor      ﬁ› |#2//|#1RESETF     |#3=|#5 Reset User Files     ﬁ
|#5› |#2//|#1RI    |#3=|#5 Read WWIV.INI          ﬁ› |#2//|#1RESETQSCAN |#3=|#5 Reset Qscan pointers ﬁ
|#5› |#2//|#1CU    |#3=|#5 Change User            ﬁ› |#2//|#1STAT       |#3=|#5 Stack/Heap in Memory ﬁ
|#5› |#2//|#1UE    |#3=|#5 User Editor            ﬁ› |#2//|#1TEDIT      |#3=|#5 Edit GFILES\<filename>ﬁ
|#5€‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹€€‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹€
