|#5WWIV 5.00 WFC COMMANDS 
|#7~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
|#2SPACE |#9Log On                 
|#2A     |#9Answer Telephone       |#2B |#9Message Sub Editor    |#2C |#9On-Line Program Editor
|#2D     |#9Download Dir Editor    |#2E |#9Email                   
|#2G     |#9G-File Section Editor  |#2H |#9Event Editor          |#2I |#9Initialize Voting Data
|#2J     |#9Conference Editor      |#2K |#9Load file for E-mail  |#2L |#9Today's Sysop Log
|#2M     |#9Read Mail              |#2N |#9Network Log           |#2O |#9Edit Text File
|#2P     |#9Pending Network data   |#2Q |#9Quit the BBS          |#2R |#9Read all email
|#2S     |#9System Status          |#2U |#9User Editor
|#2V     |#9Send Internet E-Mail   |#2W |#9Edit GFILES\filename  |#2X |#9Show Environment
|#2Y     |#9Yesterday's Sysop Log  |#2Z |#9System Activity Log   |#2/ |#9Force Net callout
|#2TAB   |#9Instance Editor        |#2` |#9Show Net Information  |#2. |#9War Dial Net connect
|#2ESC   |#9Quit BBS               |#2= |#9Reset User File       |#2! |#9Menu Editor            
|#7~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
|#9[|#2ESCAPE |#9Exit Help] [|#2RETURN |#9Next Screen] [|#2ScrLck |#9Toggle Available]
|#0