                            |#4 WWIV v5.00 Main Menu |#0
|#7ษอออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออป
|#7วฤฤฤฤฤฤ|#4Message Center|#7ฤฤฤฤฤฤยฤฤฤฤ|#4Miscellaneous|#7ฤฤฤฤฤยฤฤฤฤฤฤฤฤ|#4E-Mail|#7ฤฤฤฤฤฤฤฤฤฤฤถ
|#7บ|#2N|#1>|#0 New Msgs, All Subs|#7     ณ|#2A|#1>|#0 Auto-Message|#7       ณ|#2E|#1>|#0 E-mail User|#7           บ
|#7บ|#2P|#1>|#0 Post a Message|#7         ณ|#2B|#1>|#0 BBS List|#7           ณ|#2M|#1>|#0 Read E-mail|#7           บ
|#7บ|#2R|#1>|#0 Remove a message|#7       ณ|#2C|#1>|#0 Chat with Sysop|#7    ณ|#2F|#1>|#0 Send Feedback|#7         บ
|#7บ|#2S|#1>|#0 Scan Current Msg Base|#7  ณ|#2I|#1>|#0 System Information|#7 ณ|#2K|#1>|#0 Kill Sent E-mail|#7      บ
|#7บ|#2Z|#1>|#0 Scan All Subs Non-Stop|#7 ณ|#2L|#1>|#0 Last Caller List|#7   ณ                     |#7    บ
|#7บ|#2#|#1>|#0 Enter Number of Sub|#7    ณ|#2O|#1>|#0 Log Off|#7            รฤฤฤฤฤ|#4System Features|#7ฤฤฤฤฤถ
|#7บ|#2J|#1>|#0 Join Conference|#7        ณ|#2U|#0 or |#2~ |#1>|#0 User List|#7    ณ|#2D|#1>|#0 Change Your Defaults|#7  บ
|#7บ|#2*|#1>|#0 List Subs Available|#7    ณ|#2V|#1>|#0 Voting Booth|#7       ณ|#2G|#1>|#0 Read General Files|#7    บ
|#7บ|#2>|#0, |#2]|#0 or |#2+|#1>|#0 Advance 1 Sub|#7  ณ|#2X|#1>|#0 Toggle Xpert Mode|#7  ณ|#2T|#1>|#0 Transfer Section|#7      บ
|#7บ|#2<|#0, |#2[|#2 or |#2-|#1>|#0 Retreat 1 Sub|#7  ณ|#2Y|#1>|#0 Your Information|#7   ณ|#2.|#1>|#0 On-Line Programs|#7      บ
|#7บ|#2}|#1>|#0 Advance 1 Conference|#7   ณ|#2CTRL Y|#1>|#0 Toggle Pause|#7  ณ|#2$|#1>|#0 Use Time Bank|#7         บ
|#7บ|#2{|#1>|#0 Retreat 1 Conference|#7   ณ                 |#7     ณ                    |#7     บ
|#7บ|#2H|#1>|#0 Hop to Another Sub|#7     ณ|#2                  |#7    ณ|#2              |#7           บ
|#7วฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤมฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤมฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤถ
|#7บ|#2W|#1>|#0 WWIV Slash Menu                              |#2Ctrl T|#1>|#0 Time left On-Line|#7  บ
|#7ศอออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออผ
