
|#7    зддддддддддддддддддддд|#4 Welcome Visiting Sysops|#7 ддддддддддддддддддддд©
|#7    Ё                                                                   Ё
|#7    Ё|#2  R|#1>|#0 Read Messages  |#2  Q|#1>|#0 Quit back to Main  |#2  F|#1>|#0 Leave Feedback   |#7 Ё
|#7    Ё|#2  L|#1>|#0 List files     |#2  X|#1>|#0 Toggle Expert Mod  |#0     to Sysop         |#7 Ё
|#7    Ё|#2  N|#1>|#0 New files      |#2  ?|#1>|#0 Help                                     |#7 Ё
|#7    Ё                                                                   Ё
|#7    юддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддды
