                         |#4 WWIV v5.00 Transfer Menu |#0

|#5 ÖÄÄÄÄÄÄÄÄÄ|#4 File Transfers |#5ÄÄÄÄÄÄÄÄÄÄÄÄÒÄÄÄÄÄÄÄÄÄÄ|#4 Miscellaneous |#5ÄÄÄÄÄÄÄÄÄ·|#0
|#5 º |#7D |#1> |#2Download a File                 |#5º |#7C |#1> |#2Chat with Sysop              |#5º|#0
|#5 º |#7U |#1> |#2Upload a File                   |#5º |#7H |#1> |#2Hop to Another Directory     |#5º|#0
|#5 º |#7Z |#1> |#2Upload a File to Sysop          |#5º |#7J |#1> |#2Join File Conference         |#5º|#0
|#5 º |#7R |#1> |#2Remove a File You Uploaded      |#5º |#7K |#1> |#2Configure File List          |#5º|#0
|#5 º |#7B |#1> |#2Batch Download Bi-Directional   |#5º |#7O |#1> |#2Log Off                      |#5º|#0
|#5 ºÄÄÄÄÄÄÄÄÄ|#4 File Searches |#5ÄÄÄÄÄÄÄÄÄÄÄÄÄº |#7Q |#1> |#2Quit to Main Menu            |#5º|#0
|#5 º |#7F |#1> |#2Search by File Description      |#5º |#7T |#1> |#2Set Transfer Options         |#5º|#0
|#5 º |#7S |#1> |#2Search by File Name             |#5º |#7W |#1> |#2Menu of Slash Commands       |#5º|#0
|#5 º |#7L |#1> |#2List Files - Current Directory  |#5º |#7X |#1> |#2Toggle Expert mode (menus)   |#5º|#0
|#5 º |#7N |#1> |#2List all New Files              |#5º |#7Y |#1> |#2Your Tranfer Stats           |#5º|#0
|#5 º |#7P |#1> |#2Set New Search Date             |#5ÇÄÄÄÄÄÄÄÄ|#4 Archive Commands |#5ÄÄÄÄÄÄÄÄ¶|#0
|#5 º |#7* |#1> |#2List all Directories            |#5º |#7E |#1> |#2Extract files from Archive   |#5º|#0
|#5 º |#7>|#1,|#7]|#1,|#7+ |#1> |#2Move Forward One Directory  |#5º |#7G |#1> |#2Access Archive Command Menu  |#5º|#0
|#5 º |#7<|#1,|#7[|#1,|#7- |#1> |#2Move Backward One Directory |#5º |#7A|#1,|#7V |#1> |#2List files in Archive      |#5º|#0
|#5 º |#7{ |#1> |#2Move Backward One Conference    |#5ºÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ¶|#0
|#5 º |#7} |#1> |#2Move Forward One Conference     |#5º |#1Ctrl T - Time on Line            |#5º|#0
|#5 ÓÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÐÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ½|#0
