|#9(|#2Q|#9)uit to Main Menu
|#9(|#2S|#9)ave Message and Reply to Author
|#9(|#2R|#9)e-Read Last Message Number
|#9(|#2I|#9)gnore Last Message Read
|#9(|#2D|#9)elete Last Message Read
|#9(|#2A|#9)uto-Reply and Delete Last Message Read
|#9(|#2F|#9)orward Message to Another User (Does |#6not |#9permit comments)
|#9(|#2-|#9) Previous Message #
|#9(|#2+|#9) Next Message #
|#9(|#2G|#9)o to Specific Message Number
|#9(|#2Y|#9) Download Current Message
|#9(|#2@|#9) Reply to Different Address with quoting
