`0=============================================== New Menus by Ken Vitali ====
2-=5 WWIV v4.10 Main Menu 2=-0

5-]2 Press 5'2P5'2 to pause, (SPACE) to abort0
5'2A5' 3Auto-Message    5'2B5' 3View BBS List 0 5'2C5' 3Chat With Sysop 5'2D5' 3User Defaults 0
5'2E5' 3E-Mail a User   5'2F5' 3Leave Feedback0 5'2G5' 3G-Files Section 5'2I5' 3System Info   0
5'2K5' 3Kill Sent Mail  5'2L5' 3Last Callers  0 5'2M5' 3Read Your Mail  5'2N5' 3Global Q-Scan 0
5'2O5' 3Log Off         5'2P5' 3Post a Message0 5'2Q5' 3Quick-Scan      5'2R5' 3Remove Message0
5'2S5' 3Scan Messages   5'2T5' 3File Transfers0 5'2U5' 3User List       5'2V5' 3Voting Booth  0
5'2X5' 3Expert Mode     5'2Y5' 3Your Stats    0 5'2Z5' 3Express N-Scan  5'2*5' 3List Subs     0
5'2.5' 3On-Line Files   5'2/E5' 3Multi E-Mail 0 5'2/O5' 3Fast Log Off0

      5'2//VER5' 3WWIV Version Info                  5'2//CLS5' 3Clear Screen0
         5'2//NET5' 3NET Listing               5'2//QSCAN5' 3Clear Q-Scan Pointers0
5'2//UPLOAD5' 3Upload TEXT File as Message0

        Ctrl-O for On-Line Help                Ctrl-T for Time Display

5-Pressing a number will take you to the 5corresponding message area.0
`1============================================================================
2-=5 WWIV Message Base Commands 2=-0

2(RETURN) 3Next Message0
     5'2#5' 3Go to Message #0
     5'2-5' 3Back One Message0
     5'2A5' 3Auto-Reply in E-Mail to Last Message0
     5'2B5' 3Bypass Current Sub0
     5'2C5' 3Continuous Read0
     5'2P5' 3Post a Message0
     5'2Q5' 3Quit to Main Menu0
     5'2R5' 3Re-Read Last Message0
     5'2T5' 3Titles of Next Ten Messages0
     5'2W5' 3Publicly Reply with "Regards" to Last Message0
`2============================================================================
2-=5 WWIV Editor Commands 2=-0

2/ES  5- 3Immediate Save0
2/ESY 5- 3Immediate Save Anonymously (If allowed)0
2/ESN 5- 3Immediate Save NOT-Anonymous (If allowed)0
2/ABT 5- 3Immediate Abort0
2/CLR 5- 3Clear Message and Start Over0
2/RL  5- 3Replace Last Line0
2/TI  5- 3Re-Write Title0
2/LI  5- 3List Message so Far0
2/C:  5- 3Center Rest of Line0
2/SU/old/new  5- 3Substitute Text in Last Line0
2Ctrl-P+Digit 5- 3Change Colors0
`3============================================================================
2-=5 WWIV File Transfer Menu 2=-

5-]2 Press 5'2P5'2 to pause, and (SPACE) to abort0
5'2A5' 3Archive Listing 5'2C5' 3Page Sysop0     5'2D5' 3Download File   5'2E5' 3Extract ARC   0
5'2F5' 3Find Text       5'2G5' 3ARC Commands0   5'2L5' 3List Files      5'2N5' 3New Files     0
5'2O5' 3Log Off         5'2P5' 3New Files Date0 5'2Q5' 3Quit to BBS     5'2R5' 3Remove File   0
5'2S5' 3Search All Dirs 5'2T5' 3Trans. Options0 5'2U5' 3Upload File     5'2X5' 3Batch Download0
5'2Y5' 3Your User Stats 5'2Z5' 3UL to Sysop 0   5'2*5' 3List Dirs       5'2/O5' 3Fast Log Off 0
5'2+5' 3Advance a Dir # 5'2-5' 3Retreat a Dir0

        Ctrl-O for On-Line Help                Ctrl-T for Time Display

5-Pressing a number will take you to the 5corresponding Directory number0
`4============================================================================
2-=5 WWIV E-Mail Commands 2=-0

2(RETURN) 3Read Next Piece0
5'2-5' 3Back One Piece0
5'2D5' 3Delete Last Piece0
5'2G5' 3Go to a Piece0
5'2Q5' 3Quit to Main Menu0
5'2S5' 3Save Piece and Reply0
5'2A5' 3Auto-Reply and Delete Last Piece0
5'2F5' 3Forward Mail to Another User0
5'2I5' 3Ignore Last Piece0
5'2R5' 3Re-Read Last Piece0
`5============================================================================
2-=5 WWIV Co-Sysop Commands 2=-0

5'2//STATUS5'    3Current System Status0
5'2//IVOTES5'    3Initialize Voting Data0
5'2//LOG5'       3Today's Sysop Log0
5'2//TEDIT5'     3Text File Editor0
5'2//YLOG5'      3Yesterday's Sysop Log0
5'2//UEDIT5'     3User Status Editor0
5'2//ZLOG5'      3System Activity Log0
5'2!5'           3Validate a User0
5'2//VOTEPRINT5' 3Write Voting Info to0
              3"GFILES\VOTING.TXT"0

2-=5 WWIV Sysop Commands 2=-0

5'2//BOARDEDIT5' 3Sub-Board Editor0
5'2//EDIT5'      3Edit Any File0
5'2//DIREDIT5'   3Directory Editor0
5'2//GFILEEDIT5' 3G-File Editor0
5'2//CHAINEDIT5' 3Chain Editor0
5'2//LOAD5'      3Load a File Into Editor0
5'2//CHUSER5'    3Change Into a User0
5'2//MAILR5'     3Read All Mail Sent0
5'2//DOS5'       3Drop to Dos0
5'2//REBOOT5'    3Reboot the Computer0
5'2//STAT5'      3Stack and Heep in Memory 0
5'2//RESETF5'    3Restore All Deleted Users0
5'2//RELOAD5'    3Re-Load all Menu Files0
5'2//CHAT5'      3Change Sysop Available0
`6============================================================================
2-=5 WWIV User Editor 2=-0

5'2[5' 3Down One User     5'2]5' 3Up One User0
5'2{5' 3Search Down       5'2}5' 3Search Up0
5'2,5' 3Temp. Full Info   5'2.5' 3Full Info0
5'2/5' 3Search Specs      5'2A5' 3Change AR0
5'2C5' 3Change Callsign   5'2D5' 3Delete User0
5'2E5' 3Exemption         5'2G5' 3Change Age0
5'2I5' 3Change DAR        5'2L5' 3Real Name0
5'2M5' 3Computer Type     5'2N5' 3Name/Handle0
5'2O5' 3Change Note       5'2P5' 3Phone Number0
5'2Q5' 3Quit to Main Menu 5'2R5' 3Restore User0
5'2S5' 3Change SL         5'2T5' 3Change DSL0
5'2U5' 3Go to a User      5'2Y5' 3Sysop Sub0
5'2Z5' 3Restrictions      5'2~5' 3Kill AssPts0
5'2:5' 3Force User to Re-Enter Birthdate0
`7============================================================================
2-=5 WWIV v4.10 Waiting For Caller Menu 2=-0

1ีออออออออออออออออออออออออออออออออ[4 WFC COMMANDS 1]อออออออออออออออออออออออออออออธ0
1ณ 2(SPACE) 3Log On to BBS     5'2A5' 3Force-Answer Phone      5'2B5' 3Sub-Board Editor  1ณ0
1ณ 5'2C5' 3Edit On-Line Files    5'2D5' 3Directory Editor        5'2E5' 3Textfile Editor   1ณ0
1ณ 5'2F5' 3Shell to Dos          5'2G5' 3G-File Section Editor   5'2I5' 3Initialize Voting 1ณ0
1ณ 5'2L5' 3Today's Sysop Log     5'2M5' 3Read All Mail Sent      5'2N5' 3Network Log       1ณ0
1ณ 5'2Q5' 3Quit BBS Program      5'2R5' 3Read Feedback           5'2S5' 3System Status     1ณ0
1ณ 5'2T5' 3Terminal Program      5'2U5' 3User Editor             5'2W5' 3Write E-Mail      1ณ0
1ณ 5'2Y5' 3Yesterday's Sysop Log 5'2Z5' 3System Activity Log     5'2/5' 3Force NET Callout 1ณ0
1ณ 2(SPACE) + 5'2F5':3Fast Log On                            2ScrollLck5:3Toggle Avail 1ณ0
1ฦออออออออออออออออออออออออออออ[4 USER ON-LINE COMMANDS 1]ออออออออออออออออออออออออต0
1ณ                                                                             ณ0
1ณ 2F-1       5: 3Validate User               2Ctrl F-5   5: 3Time-out; Drop Carrier 1ณ0
1ณ 2F-2       5: 3Toggle Top of Screen Data   2F-6        5: 3Toggle User Aleart     1ณ0
1ณ 2F-3       5: 3(Dis/En)able Remote Typing  2F-7        5: 3Increase Time by 5 Min 1ณ0
1ณ 2F-4       5: 3Turn Off Chat Call          2F-8        5: 3Decrease Time by 5 Min 1ณ0
1ณ 2F-5       5: 3Drop Carrier                2F-9        5: 3Temporary 255 SL       1ณ0
1ณ 2Shft F5   5: 3Line noise; Drop Carrier    2F-10       5: 3(Dis)Engage Chat Mode  1ณ0
1ณ 2Alt F-Keys5: 3Auto-Validation Keys        2ScrollLck  5: 3Toggle Sysop Available 1ณ0
1ิอออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออพ0
`8============================================================================
5'2//MOVE5'      - 3Move File to Another Directory0
5'2//REN5'       - 3Rename a File And/Or Description0
5'2//SORT5'      - 3Sort Files Alphabetically0
5'2//UPLOAD5'    - 3Upload Files in Directory but not in Database0
5'2//UPLOADALL5' - 3Upload Command for All Directories0
`9============================================================================
5'2L5' 3List Files in Queue0
5'2R5' 3Remove File From Queue0
5'2D5' 3Download Files0
5'2Q5' 3Quit to File Transfer Menu0
`10===========================================================================
2L 5- 3Only 1 Logon per Day0
2C 5- 3Can't Page for Chat0
2M 5- 3Posts Require Sysop Validation0
2A 5- 3Restricted from Automessage0
2* 5- 3Restricted from Anonymous Posting0
2P 5- 3Cannot Post Messages0
2E 5- 3Cannot Send E-Mail0
2V 5- 3Restricted from Voting0
2K 5- 3Un-Used Restriction0
2N 5- 3Restricted from Network access0
2U 5- 3Restricted to Sysop Dir Uploads0
`11===========================================================================
5'2P5' 3Print Current Line0
5'2L5' 3List All Lines0
5'2I5' 3Insert Lines0
5'2D5' 3Delete Lines0
5'2+5' 3Forward0
5'2-5' 3Backward0
5'2Q5' 3Quit Editing0
5'2S5' 3Save Message0
5'2C5' 3Clear Message0
`12===========================================================================
5'2A5' 3Add to List0
5'2D5' 3Delete From List0
5'2E5' 3Send E-Mail0
5'2L5' 3List the List0
5'2Q5' 3Quit0
`13===========================================================================
2-=5 WWIV Message Base Commands 2=-0

2(RETURN) 3Next Message0
     5'2#5' 3Go to Message #0
     5'2-5' 3Back One Message0
     5'2A5' 3Auto-Reply in E-Mail to Last Message0
     5'2B5' 3Bypass Current Sub0
     5'2C5' 3Continuous Read0
     5'2N5' 3Permanent Message Status0
     5'2P5' 3Post a Message0
     5'2Q5' 3Quit to Main Menu0
     5'2R5' 3Re-Read Last Message0
     5'2T5' 3Titles of Next Ten Messages0
     5'2U5' 3Un-Anonymous Message Status0
     5'2V5' 3Validate Author of Last Message0
     5'2W5' 3Publicly Reply with "Regards" to Last Message0
`14===========================================================================
5'2A5' 3Add to Temporary ARC File0
5'2D5' 3Download Temporary ARC File0
5'2L5' 3List Files in Directory0
5'2Q5' 3Quit to Transfer Menu0
5'2R5' 3Remove File(s)0
5'2V5' 3View Temporary ARC File0
5'2T5' 3Text Download File(s)0
