    Here is a general overview of how WWIV BBS software operates.

    The BBS is divided into three main areas.  When you finish reading this
message, you'll be at the |#2Main Menu|#0, which contains BBS utility functions,
system bulletins, and local/networked public and private messages.  The BBS
has an wide assortment of message area topics.  You can view the available
areas with the <*> key.  Message forums are separated into "conferences" to
help you find them, and the <J>oin command allows you to change conferences.
If you don't see topic that interest you, drop me a note and I'll surely find
networked areas with others sharing your interests.

    The |#2Game Area|#0 is accessed by hitting <.> at the Main Menu.  There are
many games to play online, competing against the BBS and other users.  Some
are played against users on other systems, too!  My favorites are Scrabble and
Tradewars, but have fun trying them all!

    Uploads and downloads are done in the |#2Transfer Area|#0, accessed by
hitting <T> at the Main Menu.  Like the message areas, the file areas are
organized into conferences and directories.  Again, <J>oin and <*> command
move you around to the area you want.  Other common commands are <L>ist to
list the files in a directory, <D>ownload and <V>iew Archives.  There is no
upload or download ratio to satisfy here, but I ask if you come across a
program which you feel others would enjoy, please share it.

    I hope you enjoy the BBS!  Your security level allows access to all
file, game, and message areas.  Let me know if there's something special
you're looking for but can't find.  I want the BBS to grow to meet your needs.
Make yourself at home, and I hope you call often!

