6Welcome New User!  5We are glad to have you here at Mystic Rhythms!
7컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴
1You have chosen to register as a new user on Mystic Rhythms BBS.

9You will now be asked a few questions about yourself.  Please
9fill these out truthfully and to the best of your ability.
9The information collected here, is not used for any marketing related
9activities, and is not distributed to anyone.


7컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴
