

You must install a telnet client application that supports ANSI color and
graphics to use all the features of this system.  Here are some shareware
and freeware clients I have used and can recommend:

    Zap-O-Comm
        http://www.emtec.com/zoc/index.html


    CRT
        http://www.vandyke.com/download/index.html


    HyperTerm (Personal Edition)
        http://www.hilgraeve.com/htpe.html



