|#1L |#3- |#5Only 1 Log On per Day             |#1E |#3- |#5Can't Send E-Mail
|#1C |#3- |#5Can't Page for Chat               |#1V |#3- |#5Restricted from Voting Section
|#1M |#3- |#5Posts Require Sysop Validation    |#1K |#3- |#5Chat Room Restriction
|#1A |#3- |#5Restricted from Auto-Message      |#1N |#3- |#5Restricted from Network Access
|#1* |#3- |#5Restricted from Anonymous Posting |#1U |#3- |#5Restricted to Sysop Dir Uploads|#0
|#1P |#3- |#5Can't Post Messages|#0
