
|#5€ﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂ|#4 TRANSFER SECTION SYSOP COMMANDS |#5ﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂ€|#0
|#5›|#3"|#1//MOVE|#3"      = |#5Move a File to Another Directory                   ﬁ|#0
|#5›|#3"|#1//REN|#3"       = |#5Rename a File And/Or Change its File Description   ﬁ|#0
|#5›|#3"|#1//RSORT|#3"     = |#5Sort Files Oldest to Newest                        ﬁ|#0
|#5›|#3"|#1//SORT|#3"      = |#5Sort Files Alphabetically, or by Date of Upload    ﬁ|#0
|#5›|#3"|#1//UPLOAD|#3"    = |#5Add all Files in Current Directory Path to Databaseﬁ|#0
|#5›|#3"|#1//UPLOADALL|#3" = |#5Add all Files in All Directory Paths to Database   ﬁ|#0
|#5›|#3"|#1//UPLOADFILE|#3"= |#5Import File Descriptions from Another BBS Software ﬁ|#0
|#5›|#3"|#1//|#2A|#1llow|#2E|#1dit|#3" = |#5Edit ALLOW.DAT                                     ﬁ|#0
|#5›|#3"|#1//READIDZ|#3"   = |#5Read in File as Extended Descriptions              ﬁ|#0
|#5›|#3"|#1//|#2R|#1EMOVE|#2N|#1T|#3"  = |#5Remove some/all N/A files in transfer area         ﬁ|#0
|#5›|#3"|#1^|#3"           = |#5List Devices                                       ﬁ|#0
|#5›|#3"|#1.|#3"           = |#5View DSZ Log File                                  ﬁ|#0
|#5›|#3"|#1M|#3"           = |#5Same as //MOVE Command                             ﬁ|#0
|#5›|#3"|#1U|#3"           = |#5Upload file in Directory using File_idz            ﬁ|#0
|#5€‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹€|#0
