                     ÚÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ¿
                     ³ Mystic Rhythms System Information ³
                     ÀÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÙ

         ş WWIV Bulletin Board Software 5.00 Alpha

         Mystic Rhythms is a BBS designed for the technical side of
         computing, as well for games and general entertainment.
         From discussions on Programming to the newest games and
         chat Mystic Rhythms is easily the best equipped BBS If at any 
         time you have  a comment or suggestion to help improve the BBS, 
         feel free  to send <F>eedback to me.  

	 Mystic Rhythms BBS is still being constructed.  Please be 
         patient and let me know what can be improved.

                        ÚÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ¿
                        ³ Press [Enter] to Continue. ³
                        ÀÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÙ
