
|#3ÖÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ·|#0
|#3º|#1     Download Commands                |#3º|#0
|#3ÇÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ¶|#0
|#3º|#5 L |#1>|#2  List files in Queue             |#3º|#0
|#3º|#5 R |#1>|#2  Remove files from Queue         |#3º|#0
|#3º|#5 Q |#1>|#2  Quit to Transfer Menu           |#3º|#0
|#3º|#5 C |#1>|#2  Clear download Queue            |#3º|#0
|#3º|#5 D |#1>|#2  Download Queue                  |#3º|#0
|#3º|#5 U |#1>|#2  Upload Files                    |#3º|#0
|#3º|#5 B |#1>|#2  Bi-directional transfer         |#3º|#0
|#3ÓÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ½|#0

