|#9 Sub:                                     Msg#: [XX of YY]
|#9From:                                     Date: 
|#9Subj: 
|#9 Sys:                                     Loc:  
|#9Info: 
|[7;1H|#2|{msg.message_area}|[49;1H|#9[|#2|{msg.message_number}|#9 of |#2|{msg.total_messages}|#9]
|[7;2H|#1|{msg.from}|[49;2H|#1|{msg.date}
|[7;3H|#2|{msg.title}
|[7;4H|#1|{msg.sys}|[49;4H|{msg.loc}|#0|{set num_header_lines 5}