 |#2                          Editor Menu Commands
 |#7~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
 |#1ESCAPE     |#9 Edit Menu (This Menu)    |#1ESCAPE + S |#9 Save Message
 |#1ESCAPE + Q |#9 Quote text from message. |#1ESCAPE + A |#9 Abort Message (Quit)


 |#2                        Movement and Key Editing
 |#7~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
 |#1ARROW KEYS |#9 Move around              |#1PGUP/PGDN    |#9 Page up, Page Down 
 |#1HOME       |#9 Beginning of Line        |#1END          |#9 End of Line
 |#1CTRL-A     |#9 Beginning of Line        |#1CTRL-E       |#9 End of Line
 |#1CTRL-D     |#9 Delete Line              |#1CTRL-K       |#9 Delete to End of Line
 |#1CTRL-I     |#9 Toggle INS/OVR Mode      |#1CTRL-L       |#9 Redraw Screen     
 |#1CTRL-P+0-9 |#9 Change Color to Digit
 |#1CTRL-P+Control{A,D,F} |#9 Execute macro (control-A, control-D or control-F)
