[2J|#1Side menu colors
|#2A|#3] |#7Non-selected 'highlighted' color :       |#2B|#3] |#7Non-selected color          :
|#2C|#3] |#7Selected 'highlighted' color     :       |#2D|#3] |#7Selected color              :

|#1Other colors
|#2E|#3] |#7Color of 'þ' when file is tagged :       |#2F|#3] |#7Color of file number       :
|#2G|#3] |#7'Found' text foreground color    :       |#2H|#3] |#7Found background color     :
|#2I|#3] |#7The color of the 'current' file  :

|#1Other junk
|#2J|#3] |#7Max screen lines to show (0=all) :       |#2K|#3] |#7Min extended lines to show :

|#1Toggles...
|#2L|#3] |#7Allow user to edit .CFL:                 |#2M|#3] |#7Request file is        :
|#2N|#3] |#7Colorize found text is :                 |#2O|#3] |#7Search extended is     :
|#2P|#3] |#7Simple search is       :                 |#2R|#3] |#7Configurable lists are :
|#2S|#3] |#7Check file existance   :
