

You must install a telnet client application that supports ANSI color and
graphics to use all the features of this system.  Here are some shareware
and freeware clients I have used and can recommend:

    NetRunner
         http://mysticbbs.com/downloads.html   [win32, linux]

    SyncTerm
         http://syncterm.bbsdev.net/     [mac, win32, linux]

    Zap-O-Comm
         http://www.emtec.com/zoc/index.html   [win32, mac]

