|#2                      WWIV QWK Off-Line Reader Menu
|#7~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

|#1D|#9)|#9ownload Qwk Packet
|#1C|#9)|#9onfig Qwk settings
|#1U|#9)|#9pload Reply Packet
|#1S|#9)|#9 Config Subs to include
|#1B|#9)|#9i-Transfer of QWK and Reply packet
|#1%|#9)|#9 Set percent of all messages to download (Read OR Not)
|#1Q|#9)|#9uit to Main Menu