|#2      WWIV Sysop Message Base Commands
|#7~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
|#2(ENTER)|#9Read Next Message            
|#2#      |#9Go to Message # Entered       
|#2-      |#9Back Up 1 Message #           
|#2A      |#9E-Mail Author of Last Message 
|#2B      |#9Bypass (Skip) Current Sub (For N-Scan) 
|#2C      |#9Continuous Message Read                
|#2D      |#9Delete Current Message #               
|#2E      |#9Save Current Message to Disk        
|#2F      |#9Find specific text in messages      
|#2L      |#9Load a File as a Post               
|#2M      |#9Move Message to Another Sub         
|#2N      |#9Not Auto-purgeable (toggle status)  
|#2P      |#9Post a Public Message in Current Sub
|#2Q      |#9Quit to Main Menu                   
|#2R      |#9Re-Read Last Message #              
|#2T      |#9See Titles of Next 15 Messages      
|#2U      |#9Make Current Message NOT Anonymous  
|#2W      |#9Reply with "Regards" to Last Message
|#2X      |#9Toggle Net Pending Status           
|#2Y      |#9Download Last Message               
|#2@      |#9Reply to Different Address          
