|#5WFC COMMANDS 
|#7===============================================================================
|#2SPACE |#9Log On                |#2ESC   |#9Quit BBS              
|#2` |#9Show Net Information      |#2/ |#9Force Net callout     |#2' |#9Print Net Logs      
|#2B     |#9Message Sub Editor    |#2C |#9Chains/Doors Editor   |#2D |#9Download Dir Editor
|#2E     |#9Email                 |#2G |#9G-File Section Editor |#2H |#9Event Editor          
|#2J     |#9Conference Editor     |#2K |#9Load file for E-mail  |#2L |#9Today's Sysop Log
|#2M     |#9Read Mail             |#2N |#9Network Log           |#2O |#9Edit Text File
|#2P     |#9Pending Network data  |#2Q |#9Quit the BBS          |#2R |#9Read all email
|#2S     |#9System Status         |#2T |#9Run Terminal Program
|#2V     |#9Initialize Vote Data  |#2Y |#9Yesterday's Sysop Log |#2Z |#9System Activity Log
|#7===============================================================================
|#9[|#2ESCAPE |#9Exit Help] [|#2RETURN |#9Next Screen] [|#2ScrLck |#9Toggle Available]
|#0
