|#4Your User Information|[K|#0


|#9Your name      : |#5|{user.name} |#9#|#2|@#
|#9Phone number   : |#2|@p
|#9Mail Waiting   : |#2|@M
|#9Security Level : |#2|@S
|#9Transfer SL    : |#2|@d

|#9Date Last On   : |#2|@L
|#9Times on       : |#2|@l
|#9On today       : |#2|@O
|#9Messages posted: |#2|@m
|#9E-mail sent    : |#2|@E
|#9Time spent on  : |#2|@o |#9Minutes
|#9Uploads        : |#2|@K|#9k in |#2|@U |#9files
|#9Downloads      : |#2|@k|#9k in |#2|@D |#9files
|#9Transfer Ratio : |#2|@z

|{pausescr}
