|#3The file you attempted to download is offline.

|#2If you request this file when prompted, a message is sent to the sysop
|#2and the file will be restored.  Check again in the next few days.

|#2If you choose not to request it, no one will ever know you tried to mark
|#2this offline file. <G>

|#1In any event, please do not request the same file OVER and OVER.  If I
|#1haven't restored it, it must be missing....


