|#5WWIV 5.00 USER ON-LINE COMMAND:
|#7~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
|#2F1        |#9 Edit User Information       |#2CTRL+F5  |#9 Time-out; Drop Carrier   
|#2F2        |#9 Toggle Top of Screen Data   |#2F6       |#9 Toggle User Alert        
|#2F3        |#9 (Dis/En)able Remote Typing  |#2F7       |#9 Decrease User's Time by 5
|#2F4        |#9 Turn Off Chat Call          |#2F8       |#9 Increase User's Time by 5
|#2F5        |#9 Drop Modem Carrier          |#2F9       |#9 Temporary Sysop Access   
|#2SHIFTF5   |#9 Line Noise; Drop Carrier    |#2F10      |#9 (Dis)Engage 2-Way Chat   
|#2ALT+F-Keys|#9 Auto-Validation Keys        |#2CTRL+F10 |#9 (Dis)Engage Regular Chat 
|#2ScrollLck |#9 Toggle Sysop Availability
|#7~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
|#9[|#2ESCAPE |#9Exit Help] [|#2RETURN |#9Next Screen] [|#2ScrLck |#9Toggle Available]
|#0