|#9(|#2Q|#9)uit to Main Menu
|#9(|#2S|#9)ave Mail and Reply to Author
|#9(|#2R|#9)e-Read Last Mail #
|#9(|#2I|#9)gnore Last Mail Read
|#9(|#2D|#9)elete Last Mail Read
|#9(|#2A|#9)uto-Reply and Delete Last Mail Read
|#9(|#2F|#9)orward Mail to Another User; does not permit comments
|#9(|#2-|#9) Previous Mail #|#0
|#9(|#2+|#9) Next Mail #|#0
|#9(|#2G|#9)o to Specific Mail #
|#9(|#2E|#9)xtract this Mail
|#9(|#2M|#9)ove this Mail to a Sub-board
|#9(|#2Z|#9)ap Current Mail; does not send "So and So read your message."
|#9(|#2P|#9)urge all mail from Author.
|#9(|#2V|#9)alidate Author
|#9(|#2U|#9)edit Author
|#9(|#2O|#9) Send Form Letter to Author
|#9(|#2L|#9)oad File in Workspace (no quoting)
|#9(|#2C|#9) Concise Uedit Author
|#9(|#2N|#9) Add Author as Net-Subscriber
|#9(|#2Y|#9) Download this Mail
|#9(|#2@|#9) Reply to Different Address with quoting
