
|#3ÖÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ·|#0
|#3º|#1 Commands Preceeded by One Slash      |#3º|#0
|#3ÇÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ¶|#0
|#3º|#5 O |#1>|#2  Log Off without Logoff Message  |#3º|#0
|#3º|#5 S |#1>|#2  Zip Up a Listing Of All Files   |#3º|#0
|#3º|#5 A |#1>|#2  List All New Files              |#3º|#0
|#3º|#5 T |#1>|#2  Test an Archive                 |#3º|#0
|#3º|#5 V |#1>|#2  Scan an Archive for Viruses     |#3º|#0
|#3ÓÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ½|#0

|#3ÖÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ·|#0
|#3º|#1 Commands Preceded by Two Slashes|#3    º|#0
|#3ÇÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ¶|#0
|#3º|#5 Who |#1>|#2 Who is On-Line|#3                º|#0
|#3ÓÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ½|#0

|#3ÖÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ·|#0
|#3º|#1 Other Commands Available|#3            º|#0
|#3ÇÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ¶|#0
|#3º|#5 . |#1>|#2 Show WWIVdsz.LOG if it exists|#3   º|#0
|#3º|#5 ~ |#1>|#2 List users            |#3          º|#0
|#3ÈÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍ¼|#0
