|#2         WWIV Message Base Commands
|#7~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
|#2(ENTER)  Read Next Message             
|#2#        Go to Message # Entered              
|#2-        Back Up 1 Message #                  
|#2A        E-Mail Author of Last Message        
|#2B        Bypass (Skip) Current Sub (For N-Scan) 
|#2C        Continuous Message Read                
|#2F        Find Text in headers and messages      
|#2P        Post a Public Message in Current Sub   
|#2Q        Quit to Main Menu                      
|#2R        Re-Read Last Message #                 
|#2T        See Titles of Next 15 Messages       
|#2W        Reply with "Regards" to Last Message 
|#2Y        Download Last Message                

