 Replacable parameters:

  Param     Description                       Example
  ---------------------------------------------------------------------
   %%       A single '%'                      "%"
   %1-%5    Specified passed-in parameters
   %B       Com port base address, in hex     "3f8"
   %I       Com port irq, in decimal          "4"
   %M       Modem baud rate                   "14400"
   %S       Com port baud rate                "38400"
   %P       Com port number                   "1"
   %N       Instance number                   "1"
   %T       Time remaining (min)              "30"
   %C       chain.txt full pathname           "c:\wwiv\temp\chain.txt"
   %D       doorinfo full pathname            "c:\wwiv\temp\dorinfo1.def"
   %O       pcboard full pathname             "c:\wwiv\temp\pcboard.sys"
   %A       callinfo full pathname            "c:\wwiv\temp\callinfo.bbs"
   %R       door full pathname                "c:\wwiv\temp\door.sys"
   %K       gfiles comment file for archives  "c:\wwiv\gfiles\comment.txt"

