
|#2 WWIV User File Editor |#0

|#5€ﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂ€€ﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂ€|#0
|#5›|#1[|#3> |#5Down 1 User #                       ﬁ›|#1]|#3> |#5Up 1 User #                      ﬁ|#0
|#5›|#1{|#3> |#5Search Users in Decreasing Order    ﬁ›|#1}|#3> |#5Search Users in Increasing Order ﬁ|#0
|#5›|#1,|#3> |#5Toggle Temporary Full Information   ﬁ›|#1.|#3> |#5Toggle Full Information          ﬁ|#0
|#5›|#1/|#3> |#5User Search Specifications          ﬁ›|#1A|#3> |#5Toggle Current User's ARs        ﬁ|#0
|#5›|#1C|#3> |#5Change Current User's Callsign      ﬁ›|#1D|#3> |#5Delete Current User's Account    ﬁ|#0
|#5›|#1E|#3> |#5Change Current User's Exemption     ﬁ›|#1F|#3> |#5Change User's Electronic Address ﬁ|#0
|#5›|#1G|#3> |#5Change Current User's Age           ﬁ›|#1H|#3> |#5Change User's Password           ﬁ|#0
|#5›|#1I|#3> |#5Toggle Current User's DAR           ﬁ›|#1L|#3> |#5Change Current User's Real Name  ﬁ|#0
|#5›|#1M|#3> |#5Change Current User's Comp. Type    ﬁ›|#1N|#3> |#5Change Current User's Name/Handleﬁ|#0
|#5›|#1O|#3> |#5Change Current User's Sysop Note    ﬁ›|#1P|#3> |#5Change Current User's Phone #    ﬁ|#0
|#5›|#1Q|#3> |#5Quit to Main Menu                   ﬁ›|#1R|#3> |#5Restore Current User (If Deleted)ﬁ|#0
|#5›|#1S|#3> |#5Change Current User's SL            ﬁ›|#1T|#3> |#5Change Current User's DSL        ﬁ|#0
|#5›|#1U|#3> |#5Go to a Specific User               ﬁ›|#1V|#3> |#5Validate user on callback        ﬁ|#0
|#5›|#1W|#3> |#5Node number ( for Callback )        ﬁ›|#1X|#3> |#5Set Reg' & exp' date             ﬁ|#0
|#5›|#1Y|#3> |#5Change Current User's Sysoped Sub   ﬁ›|#1Z|#3> |#5Toggle this User's Restrictions  ﬁ|#0
|#5›|#10-9|#3>|#5Set Auto-val Security Level        ﬁ›|#1:|#3> |#5Force User to Re-Enter Some Data ﬁ|#0
|#5€‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹€€‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹€|#0
