|#7~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
|#2                           WWIV Slash Command Menu
|#7~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
|#2Commands Preceeded by Two Slashes           Commands Preceeded by One Slash 
|#2Net      |#9Show Network Boards          |#2Z  |#9Zip New Messages for Download  
|#2Who      |#9Who is on the Board          |#2O  |#9Log Off without Logoff Msg     
|#2Upload   |#9Upload a Text or Ansi File   |#2E  |#9Multiple E-mail                
|#2Qscan    |#9Mark messages as READ        |#2N  |#9Begin N-Scan at Current Sub    
|#2CLS      |#9Clear Screen                 |#2C  |#9Enter Chat Room                
|#2CM       |#9Change menu command set      |#2A  |#9New Scan Messages, All Confs   
|#2UNQSCAN  |#9Mark messages as UNread
|#2COLORS   |#9Edit Color Set
|#7~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~